import './js/owl.carousel.min.js';
import './js/owlCarousel';
import './js/mobile-menu';
import './js/dropDownMenu';
import './js/shopCart';
import './js/timer';
import './js/countdawn';
import './js/addingToCart';
import './js/PLP/paginationPLP';
import './js/PLP/selectSortPLP';
import './js/PDP/descButtonsPDP';
import './js/PDP/addingToCartPDP';
import './js/Cart/renderSideCart';
import './js/Cart/renderMainCart';
import './js/Chekout/renderProducts';

import './styles/main.scss';
import './styles/owlCarousel/owl.carousel.min.css';
import './styles/owlCarousel/owl.theme.default.min.css';
